version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${APP_NAME}_web
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${XDEBUG_PORT}:9000"
    volumes:
      - ${APP_DIR}:/var/www/html
    environment:
      - APACHE_RUN_USER=${APACHE_RUN_USER:-www-data}
      - APACHE_RUN_GROUP=${APACHE_RUN_GROUP:-www-data}
    depends_on:
      - db
    networks:
      mi_red_personalizada:
        ipv4_address: 172.16.0.10

  db:
    image: mysql:${DB_VERSION}
    container_name: ${APP_NAME}_db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ${DB_INIT}:/docker-entrypoint-initdb.d/roleplayinggamedb.sql
    networks:
      mi_red_personalizada:
        ipv4_address: 172.16.0.11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      mi_red_personalizada:
        ipv4_address: 172.16.0.12

volumes:
  db_data:

networks:
  mi_red_personalizada:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
